feat: added user and item controllers
Victor-Borisov/java-shareit pull request #1
Opened 2022-10-18 18:13 UTC by Victor-Borisov

2022-10-19 03:26 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку 
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём. 
Потом по степени "тяжеловестности" остальные зависимости

ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +import org.springframework.http.HttpStatus;
И про файл настроек `application.properties`, так как он не менялся, тоже тут напишу...

Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать.

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleForbiddenAccessException(AccessForbiddenException e) {
Forbidden как бы и подразумевает что доступ запрещен.
Поэтому слово `access` добавлять нет нужды: `ForbiddenException`

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleValidationException(ValidationException e) {
`ValidationException` -> `ConflictException`
Ну не все же проверки по валидации ведут к конфликтам?
Скорее все проверки по валидации ведут к `HttpStatus.BAD_REQUEST`, поэтому помимо того что надо переименовать класс надо посмотреть как он используется...

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends RuntimeException {
ObjectNotFoundException я сократил бы NotFoundException

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +public interface ItemDao {
Что касается интерфейса и методов в нем.
- проблема всех названий - не добавляй `Item`! 
Методы не висят в воздухе, они находятся в контексте класса. Поэтому это лишнее. Просто `create`, `update`

Когда ты тоже самое проделаешь и со вторым интерфейсом, то ты наверняка заметишь их сходство.
Подумай можно ли и с этим что то сделать?

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    Optional<Item> deleteItem(Integer id);
метод delete обычно просто ничего не возвращает void

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Вот такие лишние пустые строки это тоже бардак и нарушение `code style`.
Обращай на это внимание, пожалуйста!

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImplInMemory.java
> +        return items.values().stream().filter(item -> item.getOwner().getId().equals(userId)).collect(Collectors.toList());
Ну во первых эта строка перевалила за допустимые 120 символов...
А во вторых - даже если бы оно и помещалось, то всё равно лучше переносить каждый оператор на новую строку.

```
    @Override
    public List<Item> getItemsByOwner(Integer userId) {
        return items.values().stream()
                    .filter(item -> item.getOwner().getId().equals(userId))
                    .collect(Collectors.toList());
    }
```

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer id;
Кстати, почему у тебя `id` не `Long` ?

Твой сервис будет успешен и популярен! int точно не хватит для всех сущностей! ))

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
В классах Dto каждое поле (по необходимости конечно) должны быть снабжены аннотациями для валидации...
Она же у тебя подключена, почему же активно не используется?

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        //commented to pass test
Так всё дело в том что тут и не должно быть `userId` !
Всё идет из контроллера. Там тоже не нужен пользователь при выборке item по id.

Пользователь нужен при выборке всех айтемов пользователя.

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else {
Тут написано правильно... сначала условие по которому мы выходим пустые из метода, а потом код основной код.

Но при этом тебе вовсе не нужен `else` ! Просто убери его...

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getName().isEmpty()) {
Вот тут ты и пишешь валидацию вручную вместо того чтобы использовать аннотации.
Освой валидацию - это частый кейс!

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +@Slf4j
Ну ткнул ты аннотацию для логов - а логов то и нет!
Так что или убери её или оправдай её наличие!

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private String email;
Еще раз... валидация только у dto моделей...

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private boolean validateEmail(String email) {
Пучёк претензий к этому методу...

- Название. Валидация предусматривает возвращение результата. А если ты собрался просто бросать исключение по условию то лучше назвать метод честно: `throwIfExist`
- Надо не в `if` запихивать вот эту длинную цепочку, а наоборот... надо написать код так чтобы выйти на Optional и воспользовавшись им, сделать что нужно 
(попытался не дать прямого ответа, а просто подтолкнуть тебя, не знаю получится нет, в общем попробуй переделать)
- Есть метод `equalsIgnoreCase`

2022-10-19 03:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemById(@RequestHeader(HEADER_USER_ID) Integer userId,
Вот тут... пользователь не нужен.
Мы должны возвращать айтем по `id`, без учета его принадлежности

2022-10-19 05:01 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getName().isEmpty()) {
Сначала я и сделал валидацию через аннотации. Но в тестах при апдейтах может приходить только одно поле, а остальные обязательные при создании поля - null. И тесты не проходили. Пришлось убрать @NotNull и @NotBlank в аннотациях и прописать проверки только в create, чтобы они не мешали update.

2022-10-19 05:14 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Сначала не было пустых строк. Но проверки code style не проходили, выдавалось: EmptyLineSeparator: 'METHOD_DEF' should be separated from previous line. Там были указаны модули и номера строк, где не хватает пустой строки, пришлось их все добавить и сделать коммит [refactor: 'METHOD_DEF' separated from previous line](https://github.com/Victor-Borisov/java-shareit/pull/1/commits/654a436225741b86ccdf5fc008ab5f88c5ba1c13) Тогда проверки прошли

2022-10-22 17:23 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +
Кодировку указал, зависимости переместил

2022-10-22 17:24 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +import org.springframework.http.HttpStatus;
Создал application.yml, удалил application.properties

2022-10-22 17:25 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleForbiddenAccessException(AccessForbiddenException e) {
Переименовал в ForbiddenException

2022-10-22 17:25 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleValidationException(ValidationException e) {
Переименовал в ConflictException

2022-10-22 17:26 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/exceptions/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends RuntimeException {
Переименовал в NotFoundException

2022-10-22 17:27 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +public interface ItemDao {
Слово Item убрано, аналогично для UserDao. Создан общий интерфейс Dao.

2022-10-22 17:32 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    Optional<Item> deleteItem(Integer id);
Сделал void

2022-10-22 17:35 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImplInMemory.java
> +        return items.values().stream().filter(item -> item.getOwner().getId().equals(userId)).collect(Collectors.toList());
Перенос выполнен

2022-10-22 17:48 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer id;
Максимальное значение Integer равно 2147483647. Если добавлять запись каждую секунду, то этого хватит на: 2147483647/60/60/24/365 = 68 лет
Приложения столько не живут. Но переделал на Long

2022-10-22 17:50 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
Потому что убрал. Теперь сделал так, чтобы валидация работала для create и не работала для update.

2022-10-22 17:55 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        //commented to pass test
Параметр userId убран при получении айтема по itemId, начиная с контроллера

2022-10-22 17:57 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else {
else убран

2022-10-22 18:00 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getName().isEmpty()) {
Разобрался, как через аннотации включать валидацию для create и не включать для update (создан интерфейс Marker).

2022-10-22 18:00 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +@Slf4j
Убрал аннотацию для логов

2022-10-22 18:05 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private String email;
Убрал

2022-10-22 18:38 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private boolean validateEmail(String email) {
Метод переименован в throwIfExists, использован equalsIgnoreCase. Если указанного email не найдено, то ConflictException не бросается.  throwIfExists вызывается при create.  При update вызывается только, если требуется изменить email (чтобы не учитывать email изменяемого пользователя)

2022-10-22 18:39 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemById(@RequestHeader(HEADER_USER_ID) Integer userId,
userId больше не используется

2022-10-23 15:40 UTC, FanaticFiz approved these changes
Финальный комментарий на Я.Практикуме

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +}
В этом классе не хватает еще обработчика непредвиденных ошибок, максимально общего, который отлавливал бы всё.

```
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
```

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +}
И еще важно логировать произошедшее событие.
И желательно со стректрейсом, например: `log.info("500 {}", e.getMessage(), e);`

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
О, прикольно что есть такие проверки! 
Так то да методы должны быть разделены пустой строкой. 
Но точно ли надо две строки? ))

Проверь, пж, отпишись, и я тогда маякну чтобы подправили проверку...

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    List<Item> getByOwner(Long userId);
Мы хотим отдать все Item одного владельца...
Может назовём метод иначе: `ownerItems`, `allOwnerItems`, `getItems`, `userItems` ?

Если тебе нравится твой вариант, ничего не меняй...

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImplInMemory.java
> +        return items.values().stream()
Сможешь разобраться как настроить вот такое выравнивание?

```
    @Override
    public List<Item> getByOwner(Long userId) {
        return items.values().stream()
                    .filter(item -> item.getOwner().getId().equals(userId))
                    .collect(Collectors.toList());
    }
```

Кажется так куда краше выглядит...

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(item);
В идеале перед `return` добавлять пустую строку.
Это визуально отделит выход из метода.

Но если метода сразу начинается с return этого делать не нужно...

```
    @Override
    public ItemDto getItemById(Long itemId) {
        Item item = itemRepository.getById(itemId)
                                  .orElseThrow(() -> new NotFoundException("Not found item by id: " + itemId));

        return ItemMapper.toItemDto(item);
    }
```

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(groups = {Marker.OnCreate.class})
Теперь, с появлением аннотаций, не хватает пустых строк между полями...

2022-10-23 15:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        userRepository.getAll().stream()
На самом деле, очень страшное решение!
Код начнет деградировать с увеличением записей отданных в `getAll()`.
Тебе нужно иметь метод в репозитории, который найдет запись по email.

И когда мы придём к базе данных, это не будет проблемой и не придётся это переписывать.

2022-10-25 05:55 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    List<Item> getByOwner(Long userId);
Ты писал про этот интерфейс: "проблема всех названий - не добавляй Item. Методы не висят в воздухе, они находятся в контексте класса. Поэтому это лишнее".
Методы хорошо называть по действию, с глаголом. Отсюда get. Получать можно по идентификатору, по владельцу, по другим атрибутам. Поэтому ByOwner.

2022-10-25 05:55 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +}
Добавил

2022-10-25 06:41 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImplInMemory.java
> +        return items.values().stream()
Нашёл. Настройка стиля называется Align when multiline

2022-10-25 06:44 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(item);
Пустые строки перед return добавлены

2022-10-25 06:47 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(groups = {Marker.OnCreate.class})
Отделил поля пустыми строками, теперь аннотации и соответствующие поля выглядят одной группой

2022-10-26 06:00 UTC, Victor-Borisov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        userRepository.getAll().stream()
Переделано

2022-10-26 06:01 UTC, merged